language: cpp
compiler:
  - gcc
  - clang
env:
  global:
    - secure: "cz8Eo/xP13SCH6j38LE4eFqAfI7H5BUQaWaK9yObZWYxCm3M6FL6TOUJ0vecwKJoPyUuk5Z9qYwZCZstkID5Vyn1xNm5PavdZcRhhb7E9knJeBSTMLAqn51I8KL64E0lyqvqgM89knotGvjgY+HshwWYmR+f9v/sbFyVoUvBvvo="
    - secure: "Slm+HqRT+Vy0SG7E9gEShuHvNz6XWRUmBhVBLVJEaYy/0Lo2qp4OjFEWDjiJwFIiXstW2Wclds4SuewAn3Tc4x7dsY+5uaMCX7S/HPzsBCjLXUwjKasUqEGaVTIYmtFJm57hOkz6K2SLUUV4intkMiwtCiq/R0xe92QTTKkHyfo="
    - secure: "F9mibfsT3Ezk0RRsgOHy8RUO82H05REGmJKLDKdHiHE3toxykQX64oNBB8txjHoi+UF0H1Gwmk4oB/pNeILtyHdSuB7hB1Muod9wspOuKrzO7SMTGdjpPw7nDjQEmtfrZFhXEGb/3xm66uSGojhwe0RJF5mOzyfno+G8SIJyos4="
    - secure: "ZKC2yAvUcDb2nyrZQNqpLgEbi2pYFSKDn/+xIj9ZH+5nkn6iA5RT4AunK13qxuBkjIr2HJcUBtMFvk/mfpvpWynX+v9i3OhpVZCbkmcjQrATjiUcG6r95oEcex7NAM5uKd/41CqV/0fzTPc3uJgPozDJlt0wsBmCEarHiRNAoo0="
    - APT_DEPENDENCIES="doxygen doxygen-latex libltdl-dev libboost-all-dev liblog4cxx10-dev"
    - HOMEBREW_DEPENDENCIES="doxygen libtool boost log4cxx"
    - GIT_DEPENDENCIES=""
    - GH_USERNAME=thomas-moulard
    - GH_REPO=roboptim/roboptim-core
    - DEBSIGN_KEYID=5AE5CD75
    - PPA_URI="roboptim/ppa"
    - LCOV_IGNORE_RULES="*tests*"
  matrix:
    - ROBOPTIM_STORAGE_ORDER=ColMajor
    - ROBOPTIM_STORAGE_ORDER=RowMajor
notifications:
  hipchat:
    rooms:
      - secure: YH0AqP/y2L3+YkHNezAOfBNMB5QkeEYE3z5NV5k7gxqaEPEklQeMrSHLZzN1TuSyms/RuiQ6Zj0QA9D2ZxioTxTqGUQbh5c+Ia5n5GTIJZYg24uVXPS1w6uFQSyVNIZE6tJGpgf0RHzeGtejRW7Q9Ppr6e55TBnBc53fGTqJyPs=
  email: roboptim@googlegroups.com
branches:
  only:
  - master
  - debian
  - travis
  - coverity_scan
script:
  - export CMAKE_ADDITIONAL_OPTIONS="-DSTORAGE_ORDER=${ROBOPTIM_STORAGE_ORDER}"
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./.travis/run build; fi
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install:
  - ./.travis/run  before_install
  - ./.travis/dependencies/eigen-3.2
matrix:
  allow_failures:
    - compiler: clang
    - os: osx
    - env: COVERITY_SCAN_BRANCH=1
os:
  - linux
  - osx

addons:
  coverity_scan:
    project:
      name: "roboptim/roboptim-core"
      description: "Build submitted via Travis CI"
    notification_email: roboptim@googlegroups.com
    build_command_prepend: "mkdir coverity && cd coverity && cmake .."
    build_command: "make"
    branch_pattern: coverity_scan
