language: cpp
compiler:
  - clang
  - gcc
script: "./.travis.build.sh"
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update -qq
  - sudo apt-get install -qq doxygen doxygen-latex libltdl-dev libboost-all-dev liblog4cxx10-dev libeigen3-dev
  - sudo pip install cpp-coveralls --use-mirrors
after_success:
  - coveralls -e _travis/install -e _travis/build/eigen-eigen-ffa86ffb5570/ -e tests
  - git remote set-url origin https://${GH_TOKEN}@github.com/roboptim/roboptim-core.git
  - cd _travis/build/doc && ../../../cmake/github/update-doxygen-doc.sh
notifications:
  email:
    - roboptim@googlegroups.com
branches:
  only:
    - master
matrix:
  allow_failures:
    - clang
env:
  global:
    secure: "Slm+HqRT+Vy0SG7E9gEShuHvNz6XWRUmBhVBLVJEaYy/0Lo2qp4OjFEWDjiJwFIiXstW2Wclds4SuewAn3Tc4x7dsY+5uaMCX7S/HPzsBCjLXUwjKasUqEGaVTIYmtFJm57hOkz6K2SLUUV4intkMiwtCiq/R0xe92QTTKkHyfo="
